#!/usr/bin/env ruby

require 'aws-sdk'
require 'mime-types'

def notice(msg)
  STDERR.puts msg
end

unless ARGV.length > 0
  notice "Usage: #{$0} bucket"
  exit 1
end

s3 = AWS::S3.new(:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                 :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'])

bucket = s3.buckets[ARGV.first]

Dir['**/*.{html,css,js}'].each do |path|
  notice "#{path} -> #{bucket.name}/#{path}"
  bucket.objects[path].write(Pathname.new(path), :content_type => MIME::Types.of(path).first, :acl => :public_read)
end
